# Generated by Django 3.2 on 2022-10-24 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='AboutServices/', verbose_name='Image')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Date public')),
            ],
            options={
                'verbose_name': 'About Service',
                'verbose_name_plural': 'About Services',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='AboutUs/', verbose_name='Image')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Date public')),
            ],
            options={
                'verbose_name': 'About Us',
                'verbose_name_plural': 'About Us',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='Features/', verbose_name='Image')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Date public')),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('image', models.ImageField(upload_to='Partners/', verbose_name='Image')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Date public')),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PhoneNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenumber', models.PositiveIntegerField(verbose_name='Phone number')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Date public')),
            ],
            options={
                'verbose_name': 'Phone Number',
                'verbose_name_plural': 'Phone Numbers',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('image', models.ImageField(upload_to='Services/', verbose_name='Image')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Date public')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Slogan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Date public')),
            ],
            options={
                'verbose_name': 'Slogan',
                'verbose_name_plural': 'Slogans',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SloganItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='SloganItems/', verbose_name='Image')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Date public')),
                ('slogan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SloganItems', to='news.slogan', verbose_name='Slogan')),
            ],
            options={
                'verbose_name': 'Slogan Item',
                'verbose_name_plural': 'Slogan Items',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ServicesItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Date public')),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ServicesItems', to='news.services', verbose_name='Services')),
            ],
            options={
                'verbose_name': 'Service Item',
                'verbose_name_plural': 'Service Items',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail', models.EmailField(max_length=100, unique=True, verbose_name='Email')),
                ('address', models.TextField(verbose_name='Address')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Date public')),
                ('phonenumbers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phonenumbers', to='news.phonenumbers', verbose_name='Phone Numbers')),
                ('whatsapp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp', to='news.phonenumbers', verbose_name='WhatsApp')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AboutUsItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Date public')),
                ('about_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AboutUs', to='news.aboutus', verbose_name='About')),
            ],
            options={
                'verbose_name': 'About Us Item',
                'verbose_name_plural': 'About Us Items',
                'ordering': ['id'],
            },
        ),
    ]
