# Generated by Django 3.2 on 2022-11-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='AboutServices/', verbose_name='Image')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Date public')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
                'ordering': ['id'],
            },
        ),
    ]
